sudo: required
services:
  - docker

before_install:
  - docker build -t ptejaswi1995/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ptejaswi1995/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-695955792603"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "AKIA2ECRSULN7H3RP76F"
  secret_access_key: "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"


